### ISSUE TITLE
Clean-CMClientCache.ps1 commit 3f596a9 on Nov 30, 2018 : errors when multiple cache elements for the same package

### ISSUE THREAD

**Issue by denisrennes** [MEM-Zone/sccm-zone.com#1]
In Clean-CMClientCache.ps1 commit 3f596a9 on Nov 30, 2018 there is this comment:
"I don't know if there can be multiple cache items with the same ContentID"

I do know: yes it can be. In our context it is for the same package that was changed and then re-run : this creates new cache items with new location (subdirectory in the cache) where the new version is downloaded.

1. this is probably not managed at all in the function Get-CCMCachedPackages. This code can return a list, so the script then crashes:
"$PkgCacheInfo = $CacheInfo | Where-Object { $_.ContentID -eq $Package.PackageID }"

2. Managing this correctly is probably not feasible until you have a way to associate the program / package with the only true item cache that matches. (I do not see how yet)

**Comment by Ioan-Popovici** [comment]
Hmmm, I was almost sure that this will come back to haunt me. Was too lazy to test.
It can be fixed though as far as I know.
Will look into it when I come from back from vacation in February. Meanwhile you can use -ErrorAction ‘SilentlyContinue’ on the that particular commandlet to ignore the error.

**Comment by Ioan-Popovici** [comment]
Hi,

I found the problem. 

It’s not related to the content id that is handled ok in Get-CMClientCachedPackages the $PkgCacheInfo is supposed to return a list by design.
Also the cache item package association is working ok, it just returns two cache items to delete.

When investigating I found 4 other bugs, I will relaease a new version shortly.

Thanks for reporting this

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ioan-Popovici** [comment]
#Released v4.0 - 2019-03-15

## Changes

    * Fixed error on ContentID with multiple CacheElementIDs
    * [Breaking] Changed the logic of the Get-* functions
    * [Breaking] Changed the logic of the Remove* functions
    * [Breaking] Changed the parameter name of the Remove-CacheElementFunction function
    * Added Orphaned WMI cache cleanup (Previously it was disk only)
    * Some code cleanup

I have not tested this extensively, please report any errors
