### ISSUE TITLE
How to set up "usp_PivotWithDynamicColumns"?

### ISSUE THREAD

**Issue by alexchurch22** [MEM-Zone/sccm-zone.com#10]
I'm gathering the data correctly via the Hardware Inventory, but I'm unable to get the report in Reporting Services to work. The file mentions that has a few requirements that I'm not familiar with. Can you provide some basic instructions on how to meet these requirements?    

- Requires the usp_PivotWithDynamicColumns stored procedure.
- Requires SQL Property and ProductID extensions.

**Comment by Ioan-Popovici** [comment]
I’ll update the post today.

For more info look at:
https://github.com/SCCM-Zone/sccm-zone.github.io/issues/5

**Comment by Ioan-Popovici** [comment]
#Clarification

* The usp_PivotWithDynamicColumns is a stored procedure needed in for the sql report
* The SQL Property and ProductID are hardware inventory extensions for gathering sql data. If you already doing this with my old extension you need to implement the new one as the old dataset is not really compatible with the new report.

Closing request

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
