### ISSUE TITLE
[Clean-CMClientCache.ps1] Remove-CCMOrphanedCache Breaks Active Downloads

### ISSUE THREAD

**Issue by nlvw** [MEM-Zone/sccm-zone.com#12]
Just as a disclaimer this may be an edge case because it mostly effects an aggressive and automated use of this script.

If Software Center is actively downloading an application to install and this script runs then the Remove-CCMOrphanedCache function will try to delete the directories being used to download the content (Example Folders Being  "1" and "1.BDRTEMP")

Script Version = 4.0
Command Run = `.\Clean-CMClientCache.ps1 -CleanupActions All -LoggingOptions Host -Verbose`

**Comment by Ioan-Popovici** [comment]
It shouldn’t because I’m checking if the download is complete. I’ll do some tests myself and then get back to you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nlvw** [comment]
Not sure what the correct behavior is but what I have noticed is that while software center is downloading something to cache it does not exist in WMI.  In-fact it doesn't seem to be added to WMI until it finished downloading.

By WMI I'm referencing this call  `$WmiCacheInfo = $($CCMComObject.GetCacheInfo().GetCacheElements())`

**Comment by Ioan-Popovici** [comment]
I don’t think there is anything I can do about this. You could use the orphaned cache deletion which will address this issue.
