### ISSUE TITLE
[Clean-CMClientCache.ps1] Get-CCMCachedApplications Does Not Handle Uninstall Content

### ISSUE THREAD

**Issue by nlvw** [MEM-Zone/sccm-zone.com#13]
First of all thank you for this amazing script and making it publicly available!

This bug is for v4.0 version of the script which is the latest at the time of this writing.  

Through testing I noticed that the function Get-CCMCachedApplications only handles install content for deployment types.  This means that if a deployment type has separate uninstall content (which will have a different content id) the script will miss it and fail to clean it up.

Looking at the script, line 730 defines the action type of 'Install'.  If you switch that to 'Uninstall' the script correctly finds uninstall content but then misses the install content.  This also has the potential to error out since not all deployment types my have the action type of 'Uninstall'.

A potential fix would be to add another foreach statement to handle multiple action types.

Ex:
```
## Get application content ID
ForEach ($DeploymentType in $ApplicationDTs) {
  Foreach ($ActionType in $DeploymentType.AllowedActions) {
#The rest as is with ActionType using the $ActionType variable instead of a static string
```
This may solve the problem as well as handle the new repair action that can also have a separate content id.  I'm still doing testing on a fix but that's what I have so far.  If I am way off please let me  know.

**Comment by nlvw** [comment]
I was going to put in a pull request for the fix (I've tested it and it seems to be working without issue) but i'm having trouble cloning my forked repo.  I'll attach the updated PS1 script (The change is at line 727).

Edit: Zipped the wrong file / here's the correct one.[Clean-CMClientCache-Fixed.zip](https://github.com/SCCM-Zone/sccm-zone.github.io/files/3424005/Clean-CMClientCache-Fixed.zip)


If I manage to get GIT working i'll put in a pull request so it is easier to view.

**Comment by Ioan-Popovici** [comment]
Thanks! I’ll have a look at it next week. I don’t have access to my laptop until then.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ioan-Popovici** [comment]
Merged, thanks a lot for your contribution :)
Closing issue !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
