### ISSUE TITLE
Deployment status and report not matching

### ISSUE THREAD

**Issue by fcojavierm** [MEM-Zone/sccm-zone.com#16]
Hi,
I’m getting odd results
Deplyment Status shows 3 Non-compliant machines
https://imgur.com/2WJQJIo
but in the report all machines are grouped into compliant.
https://imgur.com/yXoA7V7

Sccm version is 2012

**Comment by Ioan-Popovici** [comment]
Let me get this right:

Machines that show non-compliant in the console show compliant in the report?

Can you make a screenshoot of the compliance rules you use or export the baseline so I can have a look at it?

I need to put this in my test environment so I can reproduce the issue.

Thanks
Ioan

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ioan-Popovici** [comment]
I've reproduced this, looking for the bug

**Comment by Ioan-Popovici** [comment]
I will rebuild the report and separate the compliance with actual values report that’s causing this into a different section. Compliance for that section is irrelevant since the value is gathered only if a non compliant rule is used.
