### ISSUE TITLE
SQL 2019 Reporting

### ISSUE THREAD

**Issue by RearAdm** [MEM-Zone/sccm-zone.com#18]
I have followed your steps to update our SQL version info in SCCM but our SQL 2019 server does not report having SQL 2019 installed.  I have done the following:

Added the HWI Extension to configuration.mof and compiled
Added HWI definitions to Default Client Settings and deployed an updated Client settings to the 2019 SQL server
I see the new extensions listed in Hardware Inventory Classes
I see the new views created in the SCCM database

But when I run "Get-CimClass -ClassName SQL_2019_Property", I get this error:
get-cimclass : Not found
    + CategoryInfo          : ObjectNotFound: (root\cimv2:sql_2019_property:String) [Get-CimClass], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041002,Microsoft.Management.Infrastructure.CimCmdlets.GetCimClassCommand

I can however retrieve the SQL_2017_Property and SQL_2014_Property classes from the same server.

**Comment by Ioan-Popovici** [comment]
Hi @RearAdm,

I thought I fixed that in my last commit, but it seems I missed one mistake.

Replace the SQL extension in the `configuration.mof` file, recompile and you should be golden

Here's a link to the extension:
https://snippets.cacher.io/snippet/b6321fe05d176fc1d5a3

**Comment by Ioan-Popovici** [comment]
Should be fixed closing issue.
Please let me know if you have any other problems

**Comment by RearAdm** [comment]
Thanks very much Ioan! I think that resolved the issue.
