### ISSUE TITLE
Clean-CMClientCache Not detecting or removing most content.

### ISSUE THREAD

**Issue by PhilAitman** [MEM-Zone/sccm-zone.com#19]
Hi loan,
I was looking to upgrade from the Technet version of this script (as this version seems so much more polished!) however I'm noticing in testing that most of the content in my test devices cache's is being skipped over.
I'm using the following Parameters:
Action = All 
FreeSpace = 100
OlderThan = 0
$RemovePersisted = $true
SkipSuperPeer = $false

For Example on one Server I have 10 Cache Entries mostly containing Update CAB's at around 1.5gig each some of which are from January this year, but running the script doesn't seem to detect they're to be removed.
Checking the last referenced time in WMI shows they're old.
$Cachepath = ([wmi]"ROOT\ccm\SoftMgmtAgent:CacheConfig.ConfigKey='Cache'").Location
$cache = get-wmiobject -query "SELECT * FROM CacheInfoEx" -namespace "ROOT\ccm\SoftMgmtAgent"
Foreach ($cacheitem in $cache) {
$cacheitem.contentID
[Management.ManagementDateTimeConverter]::ToDateTime($cacheitem.LastReferenced)
}

NCU00008
21 January 2020 00:40:45
448ef3f9-86e9-497b-954e-653286ad418f
01 April 2020 01:33:28
NCU00003
28 November 2019 14:14:37
NCU00003
13 February 2020 16:19:56
8a7ad16e-b78e-4b88-91fe-35362d9b69a7
02 June 2020 04:41:12
9b842fe4-2040-40fe-be18-4b88dd88950f
05 February 2020 01:50:05
381e77dc-f15f-4c71-84e1-32d60f26e71a
01 April 2020 01:32:12
a0203bcb-ff0e-42cb-99de-72f265c2426e
08 January 2020 01:25:04
24a6254e-dea0-4acd-ac4f-ae70abd62cdc
19 February 2020 01:22:35
aff2af4a-fb0d-4371-9c90-24a42b3fe359
15 February 2020 04:54:03

**Comment by PhilAitman** [comment]
Running the Script on the above server just gives me the following output.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = Root\ccm\SoftwareUpdates\UpdatesStore,'className' = CCM_UpdateStatus'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
[06-02-2020 15:27:30.843] [Main:CleanupResult] [Clean-CMClientCache] :: 

FullName          : 
Name              : 4556813
Location          : C:\Windows\ccmcache\d
LastReferenceTime : 02/06/2020 03:41:12
Size(MB)          : 
Status            : Needed



TotalDeletedSize: 0

**Comment by Ioan-Popovici** [comment]
Hmmm... thanks I'll have a look tomorrow if I can and post the results here.
I may have to get some script results from you.

**Comment by PhilAitman** [comment]
I'm more than happy to help, your Powershell FU is much greater than mine.
I've stepped through the script and can't see anything obvious to my eye except the obvious that I'm not getting any match for the updates in the cache from around Line 977

            ## Get cached update info
            ForEach ($Update in $Updates) {

                ## Show the progress
                $ProgressCounter++
                Write-Progress -Activity 'Processing Updates' -CurrentOperation $Update.FullName -PercentComplete (($ProgressCounter / $UpdateCount) * 100)

                ## Get the cache info for the update using the ContentID

                $UpdateCacheInfo = $CacheInfo | Where-Object { $_.ContentId -eq $Update.UniqueID }

Assuming I've understood the logic right I would expect the Cache item to be detected somewhere around here.

**Comment by Ioan-Popovici** [comment]
Yes, don't delete the items that are in the cache now so we can troubleshoot.
I'll look into it tomorrow :D

**Comment by RobinBeismann** [comment]
Hey @Ioan-Popovici ,

I just stumbled into the same. I verified it by checking the CCM Cache manually and found for example KB4556813 which is not being detected by this script.
I was also able to find out why this is the case.
This update is no longer included in the WMI Query `Get-CimInstance -Namespace 'Root\ccm\SoftwareUpdates\UpdatesStore' -ClassName 'CCM_UpdateStatus' ` because it is no longer held in the Windows Update Store of SCCM.
If you have the checkbox ticket to clean up expired / superseded content in your SCCM Infrastructure, it will remove some content like this from the WSUS used by the SCUP and therefor the script will be unable to resolve content that has been superseded.
I can't really think of a way to resolve this however as this information is no longer included anywhere..

**Comment by PCL-CrisKolkman** [comment]
Hello,

Is there any update on this?
When I run the script (122 folders in **ccmcache**) only 1 folder gets removed.

**Comment by Ioan-Popovici** [comment]
What parameters are you using?
I'll look into it today and add an option to remove stuff that is not in the UpdateStore class as @RobinBeismann pointed out that some of the data is no longer available there.

**Comment by PCL-CrisKolkman** [comment]
> What parameters are you using?

Hello @Ioan-Popovici,

I have tried multiple, but the latest try was:

```
Param (
    [Parameter(Mandatory = $false, Position = 0)]
    [ValidateSet('All', 'Applications', 'Packages', 'Updates', 'Orphaned')]
    [Alias('Action')]
    [string[]]$CleanupActions = 'All',
    [Parameter(Mandatory = $false, Position = 1)]
    [ValidateNotNullorEmpty()]
    [Alias('FreeSpace')]
    [int16]$LowDiskSpaceThreshold = 100,
    [Parameter(Mandatory = $false, Position = 2)]
    [ValidateNotNullorEmpty()]
    [Alias('OlderThan')]
    [int16]$ReferencedThreshold = 1,
    [Parameter(Mandatory = $false, Position = 3)]
    [switch]$SkipSuperPeer = $false,
    [Parameter(Mandatory = $false, Position = 4)]
    [switch]$RemovePersisted = $true,
    [Parameter(Mandatory = $false, Position = 5)]
    [ValidateSet('Host', 'File', 'EventLog', 'None')]
    [Alias('Logging')]
    [string[]]$LoggingOptions = @('Host', 'File', 'EventLog'),
    [Parameter(Mandatory = $false, Position = 6)]
    [string]$LogName = 'Configuration Manager',
    [Parameter(Mandatory = $false, Position = 7)]
    [string]$LogSource = 'Clean-CMClientCache',
    [Parameter(Mandatory = $false, Position = 8)]
    [switch]$LogDebugMessages = $false
)
```

The result is:

![image](https://user-images.githubusercontent.com/97805195/191201710-f72956cd-7a8a-4bcf-8e5e-6d7974305232.png)

**Comment by Ioan-Popovici** [comment]
Seems ok, it's probably because it cannot fid the status for those updates. I'll modify the script.
I'll probably ask you to run a wmi query to see if that indeed is the case

**Comment by PCL-CrisKolkman** [comment]
> Seems ok, it's probably because it cannot fid the status for those updates. I'll modify the script. I'll probably ask you to run a wmi query to see if that indeed is the case

Would be great thank you!
Just let me know and I'll run the query.

**Comment by PCL-CrisKolkman** [comment]
> Seems ok, it's probably because it cannot fid the status for those updates. I'll modify the script. I'll probably ask you to run a wmi query to see if that indeed is the case

@Ioan-Popovici Did you by any chance find some time to fix this?

**Comment by Ioan-Popovici** [comment]
Not yet, today I have some free time

**Comment by Ioan-Popovici** [comment]
Transferred issue to https://github.com/MEM-Zone/MEM.Zone/issues/7 as I'm planning to re-write the whole script.

New location of the project:
MEM.Zone/Invoke-CCMCacheCleanup
