### ISSUE TITLE
DE Application Deployments by Computer or User for Collection add TopConsoleUser0

### ISSUE THREAD

**Issue by Ioan-Popovici** [MEM-Zone/sccm-zone.com#2]
Jay-r Barrios
Hi, thanks for sharing your report working just fine. Can I ask how do I add a “TopConsoleUser0” under /* Device collection query */ I want to reference it as the PrimaryUser in my report as I want to pinpoint who’s the primary user of the computer. Thank you in advance.

**Comment by Ioan-Popovici** [comment]
Are you sure you don't want the primary user field?

**Comment by jayrbarrios** [comment]
If we can have both TopUser and PrimaryUser it would be great!

**Comment by Ioan-Popovici** [comment]
Done, added fields in all views except the package deployment view.
It's to complicated to do it there for the value it brings.
Read the changelog for more info

Cheers

**Comment by jayrbarrios** [comment]
Many thanks, Ioan!
