### ISSUE TITLE
Error On Line 831 - When No User Has Logged Onto Device

### ISSUE THREAD

**Issue by SCCMWalker** [MEM-Zone/sccm-zone.com#21]
Howdy Ioan,

I found an issue if you have no users that have logged onto the device yet, at least in my environment, you get an error when trying to populate the $Packages variable. The error is a generic failure when trying to access the namespace. I would suggest adding ErrorAction SilentlyContinue to that line as so. I will try to attach the full error if I can get to it.
$Packages = Get-CimInstance -Namespace 'Root\ccm\ClientSDK' -ClassName 'CCM_Program' -Verbose:$false -ErrorAction SilenetlyContinue

**Comment by SCCMWalker** [comment]
Here is the error I am seeing the DcmWmiProvider.log. I can trigger the CI and get the error, I then can log in and trigger it and it works. I can also log in, log off, trigger the CI and then it works as well.

In-line script returned error output: Get-CimInstance : Generic failure 
At C:\WINDOWS\CCM\SystemTemp\1ca9e7aa-5e2f-49eb-bdae-e27d4071b051.ps1:831 char:25
+ ... $Packages = Get-CimInstance -Namespace 'Root\ccm\ClientSDK' -ClassNam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (Root\ccm\ClientSDK:CCM_Program:String) [Get-CimInstance], CimException
+ FullyQualifiedErrorId : HRESULT 0x80041001,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
 ScriptProvider	12/14/2020 7:59:13 AM	12428 (0x308C)

**Comment by Ioan-Popovici** [comment]
I need to look at this script already. It's been too long. I'll try to look at it this week. There's a lot that needs changing...

**Comment by SCCMWalker** [comment]
Thanks Ioan, I am always very happy with your effort.

**Comment by Ioan-Popovici** [comment]
Transferred issue to https://github.com/MEM-Zone/MEM.Zone/issues/8 as I'm planning to re-write the whole script.

New location of the project:
MEM.Zone/Invoke-CCMCacheCleanup
