### ISSUE TITLE
Error content file HWI Extension sql server 2019

### ISSUE THREAD

**Issue by tuffgong31** [MEM-Zone/sccm-zone.com#22]
Hello,

I read the code of the file HWI extension for reporting sql server in sccm

I think the line 231 should be     Release = "2019"; and not     Release = "2017";

Thanks

**Comment by Ioan-Popovici** [comment]
Indeed it should...
Will change it tomorrow

**Comment by Ioan-Popovici** [comment]
Transferred issue to https://github.com/MEM-Zone/MEM.Zone/issues/9
