### ISSUE TITLE
Impossibly Slow

### ISSUE THREAD

**Issue by SoMuchMedia** [MEM-Zone/sccm-zone.com#23]
Trying to simplify to see what is going on. 

DECLARE @LocaleID     AS INTEGER       = 1033;
--Select * from fn_DCMDeploymentCompliantDetailsPerAsset(@LocaleID) Where TargetCollectionID='xyx002D2'
--Select top 100 * from fn_DCMDeploymentErrorDetailsPerAsset(@LocaleID)  Where TargetCollectionID='xyz002D2'
Select top 100 * from fn_DCMDeploymentErrorDetailsPerAsset(@LocaleID)

First query (compliant and most machines are compliant) 3 minutes 373K records
2nd query - 15 minutes when I killed it (should be fewer errors)
3rd query - over 4 minutes now to just get the top 100 and I killed it.

Even top 100 BLName, seems to run forever.

Thoughts?

-John

**Comment by Ioan-Popovici** [comment]
Which report is using this query?
You need to select fewer things and join it with a smaller subset on an indexed field if you want it to be faster

Try to use BL_ID or CI_ID
