### ISSUE TITLE
[CB Configuration Baseline Compliance by Configuration Item with Values] - Can't import the report into SQL 2014 SSRS instance.

### ISSUE THREAD

**Issue by KapilDham** [MEM-Zone/sccm-zone.com#6]
Can't import the report into SQL 2014 SSRS instance. I did some reading and even changed the report definition to 2010 version but no luck.
I am getting the following alert:

The definition of this report is not  valid or supported by this version of Reporting Services. The report definition  may have been created with a later version of Reporting Services, or contain  content that is not well-formed or not valid based on Reporting Services  schemas. Details: The report definition has an invalid target namespace  
'http://schemas.microsoft.com/sqlserver/reporting/2010/01/reportdefinition/'  which cannot be upgraded. (rsInvalidReportDefinition) Get Online Help

Thanks.

Kapil

**Comment by Ioan-Popovici** [comment]
You can't import it because you use a 2014 SSRS. The report definition is for a 2016 SSRS.
Changing it to a lower level (2010) will not help you in any way. You either change the definition to match your SSRS (2014) and remove the unsupported elements or... you can just upgrade your SSRS instance, which would be much easier.

**Comment by Ioan-Popovici** [comment]
Update. I removed the dependency on report definitons and was able to import. Now I see this message post import that:
The EXECUTE permission was denied on the object ‘fn_rbac_GetAdminIDsfromUserSIDs’, database ‘CM’, schema ‘dbo’.
Query execution failed for dataset ‘AdminID’. (rsErrorExecutingCommand)
 — — — — — — — — — — — — — — 
An error has occurred during report processing. (rsProcessingAborted)
Any ideas?
I looked into datasets and tried running the queries individually. somehow I get this error:
TITLE: Microsoft SQL Server Report Builder
 — — — — — — — — — — — — — — —
An error occurred while executing the query.
The EXECUTE permission was denied on the object ‘fn_rbac_GetAdminIDsfromUserSIDs’, database ‘CM’, schema ‘dbo’.

**Comment by Ioan-Popovici** [comment]
You don't have execute permission on that function. Please make sure that the account you are using for reporting has proper access to the database:

`EXECUTE AS LOGIN = 'DomainName\ReportingUserName';  
SELECT * FROM fn_my_permissions('fn_rbac_GetAdminIDsfromUserSIDs', 'OBJECT')   
    ORDER BY subentity_name, permission_name ;    
REVERT;  
GO;`

You could use the following command to grant execute on that function put I recommend to add the proper access to that account:

`GRANT SELECT ON fn_rbac_GetAdminIDsfromUserSIDs TO 'DomainName \ReportingUserName';`

**Comment by KapilDham** [comment]
I have DB Reader access for now and we are using SCCM 2016, do I need the db_datawriter access as well?

Kapil

**Comment by Ioan-Popovici** [comment]
My mistake you need EXECUTE

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
