### ISSUE TITLE
[SW SQL Server Products] - Show CPU Core count

### ISSUE THREAD

**Issue by Ioan-Popovici** [MEM-Zone/sccm-zone.com#8]
Hello Ioan,
My colleague has successfully imported this report and gotten everything to work. Thank you, this makes us look good!
Would it be possible for an updated report with the count of processor cores on the server? I tried to it is way beyond my SQL knowledge.

**Comment by Ioan-Popovici** [comment]
Waiting on issue https://github.com/SCCM-Zone/sccm-zone.github.io/issues/5

**Comment by matthewgnslue** [comment]
This data is stored in the [dbo].[v_GS_PROCESSOR] VIEW.  You can summarise this data using the below query:

SELECT
	DISTINCT(CPU.SystemName0) AS [System Name],
	CPU.[ResourceID],
	CPU.Manufacturer0 AS Manufacturer,
	CPU.Name0 AS Name,
	COUNT(CPU.ResourceID) AS [Number of CPUs],
	CPU.NumberOfCores0 AS [Number of Cores per CPU],
	CPU.NumberOfLogicalProcessors0 AS [Logical CPU Count]
 FROM
	[dbo].[v_GS_PROCESSOR] CPU
 GROUP BY
	CPU.SystemName0,
	CPU.[ResourceID],
	CPU.Manufacturer0,
	CPU.Name0,
	CPU.NumberOfCores0,
	CPU.NumberOfLogicalProcessors0

[Source](https://social.technet.microsoft.com/Forums/en-US/9017c0d7-f265-4f0f-a5ce-8b753d8e5ce7/sccm-2012-r2-query-cpu-cores-for-a-server-or-report?forum=configmanagergeneral)

You can JOIN using the [ResourceID].

**Comment by Ioan-Popovici** [comment]
Hi yeah I know thanks. I did not manage to get to it because I'm working on a new version of the report (https://github.com/SCCM-Zone/sccm-zone.github.io/issues/5).
But it will be in the query by the end of today.

**Comment by Ioan-Popovici** [comment]
Just pushed the modification on the new query. I hope I'll have the report ready by tomorrow.
Have a look and let me know if this is ok:
![Screen Shot 2019-06-19 at 18 43 04](https://user-images.githubusercontent.com/17069425/59780483-b9cc5e80-92c2-11e9-9fb3-47e1a03dd425.png)

**Comment by Ioan-Popovici** [comment]
Added in #5.
Technically it's not yet released yet but since the functionality has been added and will be released soon there is no need to keep this ticket open.
