### ISSUE TITLE
[Request] Custom Folders and User Profile(s) Size

### ISSUE THREAD

**Issue by GENICT** [MEM-Zone/sccm-zone.com#9]
For Migration Projects or other use cases, the size of custom folders created by users or the user profiles size report (with actual values) could be very useful. As described before on twitter, the CI detection scripts are stored in this Technet Forum thread https://social.technet.microsoft.com/Forums/en-US/0c315e9b-fe44-477b-9964-818a4089fb8b/folder-size-report-for-spcific-device-collection?forum=ConfigMgrCBGeneral

**Comment by Ioan-Popovici** [comment]
Of this is still needed I have some time to work on this now. If there’s no reply for 3 days I will close this issue.
